FROM centos:6

RUN : "実行コマンドを標準エラー出力に出力する" && \
    set -x && \
    : "CentOS 拡張パッケージを提供リポジトリ" && \
    yum install -y epel-release && \
    yum install -y nginx && \
    : "プロキシ設定" && \
    sed -i -e "s/location \/ {/location \/ { proxy_pass http:\/\/ip-api.com\/json;/" \
        /etc/nginx/conf.d/default.conf && \
    : "ログ出力設定" && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

#  80番ポートを公開
EXPOSE 80
# dockerコンテナはforegroundで動かさないと即停止。demon起動をOFF設定
CMD ["nginx", "-g", "daemon off;"]

