version: '3.3' # docker engineバージョンと合わせる https://docs.docker.com/compose/compose-file/
services:
  # DB
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    ports:
      - '3306:3306' #デバッグ用
    environment:
      MYSQL_ROOT_PASSWORD: root
  # nginx
  nginx:
    container_name: "nginx"
    image: nginx:1.11
    links: # 連携設定
      - mysql
      - php
  # php
  php:
    container_name: "php"
    image: php:7.1-apache
    ports:
      - '80:80' # ポート開け
    volumes:
      - ./html:/var/www/html # hostディレクトリをコンテナディレクトリへマウント
    links:
      - mysql
